#ifndef _ASM_LKL_UNISTD_H
#define _ASM_LKL_UNISTD_H

#include <uapi/asm/unistd.h>

/*
 * Unsupported system calls due to lack of support in LKL (e.g. related to
 * virtual memory, signal, user processes). We also only support 64bit version
 * of system calls where we have two version to keep the same APi across 32 and
 * 64 bit hosts.
 */
/* note(hajime): we may automate this to follow when new syscalls are added */
#define __IGNORE_restart_syscall
#define __IGNORE_exit
#define __IGNORE_execve
#define __IGNORE_lseek
#define __IGNORE_setuid
#define __IGNORE_ptrace
#define __IGNORE_kill
#define __IGNORE_dup
#define __IGNORE_times
#define __IGNORE_brk
#define __IGNORE_setgid
#define __IGNORE_geteuid
#define __IGNORE_getegid
#define __IGNORE_acct
#define __IGNORE_umount2
#define __IGNORE_setpgid
#define __IGNORE_getppid
#define __IGNORE_setsid
#define __IGNORE_setreuid
#define __IGNORE_setregid
#define __IGNORE_sethostname
#define __IGNORE_setrlimit
#define __IGNORE_getrlimit
#define __IGNORE_getrusage
#define __IGNORE_gettimeofday
#define __IGNORE_settimeofday
#define __IGNORE_getgroups
#define __IGNORE_setgroups
#define __IGNORE_mmap
#define __IGNORE_munmap
#define __IGNORE_ftruncate
#define __IGNORE_fchmod
#define __IGNORE_fchown
#define __IGNORE_getpriority
#define __IGNORE_setpriority
#define __IGNORE_statfs
#define __IGNORE_fstatfs
#define __IGNORE_syslog
#define __IGNORE_setitimer
#define __IGNORE_getitimer
#define __IGNORE_fstat
#define __IGNORE_vhangup
#define __IGNORE_wait4
#define __IGNORE_sysinfo
#define __IGNORE_clone
#define __IGNORE_setdomainname
#define __IGNORE_adjtimex
#define __IGNORE_init_module
#define __IGNORE_delete_module
#define __IGNORE_quotactl
#define __IGNORE_getpgid
#define __IGNORE_fchdir
#define __IGNORE_personality
#define __IGNORE_setfsuid
#define __IGNORE_setfsgid
#define __IGNORE_pwritev
#define __IGNORE_readv
#define __IGNORE_getsid
#define __IGNORE_sched_setparam
#define __IGNORE_sched_getparam
#define __IGNORE_sched_setscheduler
#define __IGNORE_sched_getscheduler
#define __IGNORE_sched_yield
#define __IGNORE_sched_get_priority_max
#define __IGNORE_sched_get_priority_min
#define __IGNORE_sched_rr_get_interval
#define __IGNORE_mremap
#define __IGNORE_setresuid
#define __IGNORE_getresuid
#define __IGNORE_nfsservctl
#define __IGNORE_setresgid
#define __IGNORE_getresgid
#define __IGNORE_prctl
#define __IGNORE_rt_sigreturn
#define __IGNORE_rt_sigaction
#define __IGNORE_rt_sigprocmask
#define __IGNORE_rt_sigpending
#define __IGNORE_rt_sigtimedwait
#define __IGNORE_rt_sigqueueinfo
#define __IGNORE_rt_sigsuspend
#define __IGNORE_capget
#define __IGNORE_capset
#define __IGNORE_sigaltstack
#define __IGNORE_sendfile
#define __IGNORE_pivot_root
#define __IGNORE_gettid
#define __IGNORE_readahead
#define __IGNORE_lremovexattr
#define __IGNORE_fremovexattr
#define __IGNORE_tkill
#define __IGNORE_futex
#define __IGNORE_sched_setaffinity
#define __IGNORE_sched_getaffinity
#define __IGNORE_io_setup
#define __IGNORE_io_destroy
#define __IGNORE_io_getevents
#define __IGNORE_io_submit
#define __IGNORE_io_cancel
#define __IGNORE_fadvise64
#define __IGNORE_exit_group
#define __IGNORE_lookup_dcookie
#define __IGNORE_set_tid_address
#define __IGNORE_timer_create
#define __IGNORE_timer_settime
#define __IGNORE_timer_gettime
#define __IGNORE_timer_getoverrun
#define __IGNORE_timer_delete
#define __IGNORE_clock_settime
#define __IGNORE_clock_gettime
#define __IGNORE_clock_getres
#define __IGNORE_clock_nanosleep
#define __IGNORE_tgkill
#define __IGNORE_mq_open
#define __IGNORE_mq_unlink
#define __IGNORE_mq_timedsend
#define __IGNORE_mq_timedreceive
#define __IGNORE_mq_notify
#define __IGNORE_mq_getsetattr
#define __IGNORE_kexec_load
#define __IGNORE_waitid
#define __IGNORE_add_key
#define __IGNORE_request_key
#define __IGNORE_keyctl
#define __IGNORE_ioprio_set
#define __IGNORE_ioprio_get
#define __IGNORE_inotify_add_watch
#define __IGNORE_inotify_rm_watch
#define __IGNORE_openat
#define __IGNORE_mkdirat
#define __IGNORE_mknodat
#define __IGNORE_fchownat
#define __IGNORE_unlinkat
#define __IGNORE_linkat
#define __IGNORE_symlinkat
#define __IGNORE_readlinkat
#define __IGNORE_fchmodat
#define __IGNORE_faccessat
#define __IGNORE_pselect6
#define __IGNORE_ppoll
#define __IGNORE_unshare
#define __IGNORE_set_robust_list
#define __IGNORE_get_robust_list
#define __IGNORE_splice
#define __IGNORE_sync_file_range
#define __IGNORE_tee
#define __IGNORE_vmsplice
#define __IGNORE_getcpu
#define __IGNORE_epoll_pwait
#define __IGNORE_timerfd_create
#define __IGNORE_timerfd_settime
#define __IGNORE_timerfd_gettime
#define __IGNORE_signalfd4
#define __IGNORE_eventfd2
#define __IGNORE_epoll_create1
#define __IGNORE_dup3
#define __IGNORE_pipe2
#define __IGNORE_inotify_init1
#define __IGNORE_preadv
#define __IGNORE_rt_tgsigqueueinfo
#define __IGNORE_perf_event_open
#define __IGNORE_recvmmsg
#define __IGNORE_fanotify_init
#define __IGNORE_fanotify_mark
#define __IGNORE_prlimit64
#define __IGNORE_name_to_handle_at
#define __IGNORE_open_by_handle_at
#define __IGNORE_clock_adjtime
#define __IGNORE_syncfs
#define __IGNORE_setns
#define __IGNORE_process_vm_readv
#define __IGNORE_process_vm_writev
#define __IGNORE_kcmp
#define __IGNORE_finit_module
#define __IGNORE_sched_setattr
#define __IGNORE_sched_getattr
#define __IGNORE_renameat2
#define __IGNORE_seccomp
#define __IGNORE_getrandom
#define __IGNORE_memfd_create
#define __IGNORE_bpf
#define __IGNORE_execveat
#define __IGNORE_socketpair
#define __IGNORE_accept4
#define __IGNORE_shutdown
#define __IGNORE_userfaultfd
#define __IGNORE_membarrier

int run_syscalls(void);

#endif
